-- Profile je Benutzer (z.B. Work, Home). Das aktive Profil bestimmt die Einstellungen seiner MCP-Clients.
CREATE TABLE profile (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT                   NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
    name        VARCHAR(64)              NOT NULL,
    description VARCHAR(500),
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_profile_user_name UNIQUE (user_id, name)
);

ALTER TABLE app_user ADD COLUMN active_profile_id BIGINT;
ALTER TABLE app_user ADD CONSTRAINT fk_app_user_active_profile
    FOREIGN KEY (active_profile_id) REFERENCES profile (id) ON DELETE SET NULL;

-- Überschriebene Modul-Einstellungen. Ebene USER (level_id = Benutzer) gilt für alle Profile des Benutzers,
-- PROFILE (level_id = Profil) nur dort. Globale Werte stehen weiter in settings.json.
-- setting_key: Feldschlüssel, '@enabled' (Modul an/aus) oder '@tool:<name>' (einzelnes Tool an/aus).
-- secret = TRUE: setting_value ist mit dem Schlüssel aus secret.key verschlüsselt.
CREATE TABLE module_override (
    level         VARCHAR(8)    NOT NULL,
    level_id      BIGINT        NOT NULL,
    module_id     VARCHAR(32)   NOT NULL,
    setting_key   VARCHAR(160)  NOT NULL,
    setting_value VARCHAR(20000),
    secret        BOOLEAN       NOT NULL,
    CONSTRAINT pk_module_override PRIMARY KEY (level, level_id, module_id, setting_key)
);

-- Vom Administrator gesperrte Felder: gelten nur global, Überschreibungen werden ignoriert.
-- field_key wie setting_key; '@tools' sperrt alle Tool-Schalter des Moduls.
CREATE TABLE field_lock (
    module_id VARCHAR(32)  NOT NULL,
    field_key VARCHAR(160) NOT NULL,
    CONSTRAINT pk_field_lock PRIMARY KEY (module_id, field_key)
);
