-- Benutzer der Web-UI und Eigentümer der MCP-Zugriffstokens. Portabel für H2 und PostgreSQL.
CREATE TABLE app_user (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(64)              NOT NULL,
    display_name  VARCHAR(200),
    email         VARCHAR(320),
    password_hash VARCHAR(255)             NOT NULL,
    role          VARCHAR(16)              NOT NULL,
    enabled       BOOLEAN                  NOT NULL,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_app_user_username UNIQUE (username)
);

-- Persönliche MCP-Zugriffstokens (JWT). Gespeichert wird nur die Token-ID (jti), nie das Token selbst.
CREATE TABLE api_token (
    id           VARCHAR(36)              NOT NULL PRIMARY KEY,
    user_id      BIGINT                   NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
    name         VARCHAR(100)             NOT NULL,
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    expires_at   TIMESTAMP WITH TIME ZONE,
    last_used_at TIMESTAMP WITH TIME ZONE,
    revoked_at   TIMESTAMP WITH TIME ZONE
);

CREATE INDEX ix_api_token_user ON api_token (user_id);
