-- Projekte: ein Verzeichnis auf dem Server mit Eigentümer, optional Sonar-Schlüssel und Ticket-Projekt.
-- Git, Build und Code-Graph arbeiten für angemeldete Benutzer nur mit ihren eigenen und freigegebenen Projekten.
CREATE TABLE project (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id       BIGINT                   NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
    name           VARCHAR(64)              NOT NULL,
    root_path      VARCHAR(1024)            NOT NULL,
    description    VARCHAR(500),
    sonar_key      VARCHAR(400),
    ticket_project VARCHAR(200),
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_project_owner_name UNIQUE (owner_id, name)
);

-- Freigabe eines Projekts an einen anderen Benutzer: READ (lesen) oder WRITE (auch Commit, Build, Graph-Aufbau).
CREATE TABLE project_share (
    project_id BIGINT     NOT NULL REFERENCES project (id) ON DELETE CASCADE,
    user_id    BIGINT     NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
    access     VARCHAR(8) NOT NULL,
    CONSTRAINT pk_project_share PRIMARY KEY (project_id, user_id)
);

CREATE INDEX ix_project_share_user ON project_share (user_id);
