-- Rollen mit Rechten statt einer festen Rolle je Benutzer; ein Benutzer kann mehrere Rollen haben.
-- Rechte (siehe Grants): '*' (alles), Systemrechte wie 'users.manage', 'module:*' (alle Module), 'module:<id>' (ein
-- Modul mit allen Tools), 'tool:<name>' (ein einzelnes Tool).
CREATE TABLE app_role (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(64)              NOT NULL,
    description VARCHAR(500),
    builtin     BOOLEAN                  NOT NULL,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_app_role_name UNIQUE (name)
);

CREATE TABLE role_permission (
    role_id    BIGINT       NOT NULL REFERENCES app_role (id) ON DELETE CASCADE,
    permission VARCHAR(160) NOT NULL,
    CONSTRAINT pk_role_permission PRIMARY KEY (role_id, permission)
);

CREATE TABLE user_role (
    user_id BIGINT NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
    role_id BIGINT NOT NULL REFERENCES app_role (id) ON DELETE CASCADE,
    CONSTRAINT pk_user_role PRIMARY KEY (user_id, role_id)
);

CREATE INDEX ix_user_role_role ON user_role (role_id);

-- Eingebaut: Administrator (alle Rechte, nicht änderbar). Vorbelegt und frei änderbar: Benutzer.
INSERT INTO app_role (name, description, builtin, created_at)
VALUES ('Administrator', 'Alle Rechte', TRUE, CURRENT_TIMESTAMP);
INSERT INTO app_role (name, description, builtin, created_at)
VALUES ('Benutzer', 'Alle Module, eigene Einstellungen, Projekte und Tokens', FALSE, CURRENT_TIMESTAMP);

INSERT INTO role_permission (role_id, permission) SELECT id, '*' FROM app_role WHERE name = 'Administrator';
INSERT INTO role_permission (role_id, permission) SELECT id, 'module:*' FROM app_role WHERE name = 'Benutzer';
INSERT INTO role_permission (role_id, permission) SELECT id, 'settings.own' FROM app_role WHERE name = 'Benutzer';
INSERT INTO role_permission (role_id, permission) SELECT id, 'projects.create' FROM app_role WHERE name = 'Benutzer';
INSERT INTO role_permission (role_id, permission) SELECT id, 'tokens.create' FROM app_role WHERE name = 'Benutzer';

-- Bisherige Rollen übernehmen
INSERT INTO user_role (user_id, role_id)
SELECT u.id, r.id FROM app_user u, app_role r
WHERE (u.role = 'ADMIN' AND r.name = 'Administrator') OR (u.role <> 'ADMIN' AND r.name = 'Benutzer');

ALTER TABLE app_user DROP COLUMN role;

-- Muss sein Passwort bei der nächsten Anmeldung ändern (vom Administrator gesetzt, erster Administrator).
ALTER TABLE app_user ADD COLUMN password_change_required BOOLEAN DEFAULT FALSE NOT NULL;
ALTER TABLE app_user ADD COLUMN last_login_at TIMESTAMP WITH TIME ZONE;

-- TOKEN: persönliches Token aus „Mein Konto“; SESSION: Anmeldung einer Desktop-App, endet mit der Abmeldung.
ALTER TABLE api_token ADD COLUMN kind VARCHAR(16) DEFAULT 'TOKEN' NOT NULL;
